fragment GlobalInfo on Global {
  id
  gameFactory
}

fragment CharacterInfo on Character {
  id
  characterId
  account
  player
  name
  experience
  uri
}

fragment GameMetaInfo on Game {
  id
  uri
  owners
  masters
  experience
  characters {
    id
  }
  classes {
    id
  }
  items {
    id
  }
}

fragment FullGameInfo on Game {
  id
  classesAddress
  itemsAddress
  uri
  owners
  masters
  experience
  characters {
    ...CharacterInfo
  }
  classes {
    id
    classId
    name
  }
  items {
    id
    itemId
    name
  }
}
