fragment GlobalInfo on Global {
  id
  gameFactory
}

fragment CharacterInfo on Character {
  id
  characterId
  account
  player
  name
  experience
  uri
  heldClasses {
    classEntity {
      ...ClassInfo
    }
  }
}

fragment ClassInfo on Class {
  id
  classId
  name
  uri
}

fragment ItemInfo on Item {
  id
  itemId
  name
  uri
  supply
}

fragment GameMetaInfo on Game {
  id
  uri
  owners
  masters
  experience
  characters {
    id
  }
  classes {
    id
  }
  items {
    id
  }
}

fragment FullGameInfo on Game {
  id
  classesAddress
  itemsAddress
  uri
  owners
  masters
  experience
  characters {
    ...CharacterInfo
  }
  classes {
    ...ClassInfo
  }
  items {
    ...ItemInfo
  }
}
