fragment GlobalInfo on Global {
  id
  gameFactory
}

fragment CharacterInfo on Character {
  id
  characterId
  account
  player
  jailed
  removed
  approved
  experience
  uri
  heldClasses {
    classEntity {
      ...ClassInfo
    }
  }
  heldItems {
    amount
    item {
      ...ItemInfo
    }
  }
  equippedItems {
    heldItem {
      amount
    }
    item {
      ...ItemInfo
    }
  }
}

fragment ClassInfo on Class {
  id
  classId
  uri
  claimable
  holders {
    id
  }
}

fragment ItemRequirementInfo on ItemRequirement {
  assetCategory
  assetAddress
  assetId
  amount
}

fragment ItemInfo on Item {
  id
  itemId
  uri
  soulbound
  supply
  totalSupply
  merkleRoot
  requirements {
    ...ItemRequirementInfo
  }
  holders {
    id
  }
  equippers {
    id
  }
}

fragment GameMetaInfo on Game {
  id
  uri
  owner {
    address
  }
  admins {
    address
  }
  masters {
    address
  }
  experience
  characters {
    id
    player
  }
  classes {
    id
  }
  items {
    id
  }
}

fragment FullGameInfo on Game {
  id
  classesAddress
  itemsAddress
  experienceAddress
  characterEligibilityAdaptor
  uri
  owner {
    address
  }
  admins {
    address
  }
  masters {
    address
  }
  experience
  characters {
    ...CharacterInfo
  }
  classes {
    ...ClassInfo
  }
  items {
    ...ItemInfo
  }
}
