query GetGlobal($id: ID!) {
  global(id: $id) {
    ...GlobalInfo
  }
}

query GetGames($limit: Int, $skip: Int) {
  games(first: $limit, skip: $skip, orderBy: startedAt, orderDirection: desc) {
    ...GameMetaInfo
  }
}

query GetGame($gameId: ID!) {
  game(id: $gameId) {
    ...FullGameInfo
  }
}
