query GetGlobal {
  globals {
    ...GlobalInfo
  }
}

query GetGames($limit: Int, $skip: Int) {
  games(first: $limit, skip: $skip, orderBy: startedAt, orderDirection: desc) {
    ...GameMetaInfo
  }
}

query GetGame($gameId: ID!) {
  game(id: $gameId) {
    ...FullGameInfo
  }
}

query GetGameWithMasters($gameId: ID!) {
  game(id: $gameId) {
    masters {
      address
    }
  }
}
