import { uriToHttp } from '@/utils/helpers';

export enum TraitType {
  BODY = 'BODY',
  EYES = 'EYES',
  HAIR = 'HAIR',
  CLOTHING = 'CLOTHING',
  MOUTH = 'MOUTH',
}

export type Trait = {
  color: string;
  image: string;
  trait_type: TraitType;
  variation: string;
  z_index: number;
};

export const TRAITS: { [key: string]: Trait } = {
  ['1_Basic_a']: {
    color: 'a',
    image: 'ipfs://bafybeieqpd5jiuun7hcqgsetmjyyf6hiy3efjemvvjhyarcoriozvtpwam',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_b']: {
    color: 'b',
    image: 'ipfs://bafybeic4ccrkamv52cf3eocplbmnqlrnnekx6tc6hieapoqw7rb7454i4m',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_c']: {
    color: 'c',
    image: 'ipfs://bafybeicalhwsj7lms7mlnm76gtlglotmzhlwuvo4rhss2akf2nwklste64',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_d']: {
    color: 'd',
    image: 'ipfs://bafybeibh72ppqnslmgvqebdbq2vpvqryw6rwxtcwhuohdcnqwotxd6g2lu',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_e']: {
    color: 'e',
    image: 'ipfs://bafybeid4vivesohwhzlwqnhgpiwpzmuxmhbd25pdr2pcy2iuar3virk454',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_f']: {
    color: 'f',
    image: 'ipfs://bafybeibpwwzwxckkwfcewb3rzt55jnktx7gwbeheiidztd4qmbgeyzuok4',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_g']: {
    color: 'g',
    image: 'ipfs://bafybeiekl7tw6zbakq7j4tssktqsxue42eefmov7t2s3h4sgbu6sonjtvy',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['1_Basic_h']: {
    color: 'h',
    image: 'ipfs://bafybeibkomir3jinrmptqjluxgpqnaa2k2llnisve6jt2tzj4g5coiqtae',
    trait_type: TraitType.BODY,
    variation: 'Basic',
    z_index: 1,
  },
  ['2_Basic_a']: {
    color: 'a',
    image: 'ipfs://bafybeia3f36ljwnjfd7hlclqffpeuvsq6bgpvopkqqirrrin4iawaeziae',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Basic_b']: {
    color: 'b',
    image: 'ipfs://bafybeifewz2vav4gdosj7ilxdop2n77r3f3be6eg7zbzbcgqysogvj6nnq',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Basic_c']: {
    color: 'c',
    image: 'ipfs://bafybeifabh4atbedh7nmxyr35zjhjplvjwybewelubpmyugsplzlahjxzq',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Basic_d']: {
    color: 'd',
    image: 'ipfs://bafybeigjjttg35mti26jovdayyy3f463fq3pa4f3ozms5a2htsryzo27dm',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Basic_e']: {
    color: 'e',
    image: 'ipfs://bafybeic37thlbjghoe6nrkdo5yk36tacqh7rt7q3zzubqa3g542t6uvzvy',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Basic_f']: {
    color: 'f',
    image: 'ipfs://bafybeial3aq6s2jcb37p4awfmu2bloszjt7rqbzbmorpzkxbqn6vs27iyu',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Basic_g']: {
    color: 'g',
    image: 'ipfs://bafybeifwrhmj7zkpn6va2mgr4pabicooddkgpkbmdypfcnkmsuoxlwcqm4',
    trait_type: TraitType.EYES,
    variation: 'Basic',
    z_index: 2,
  },
  ['2_Eyepatch_a']: {
    color: 'a',
    image: 'ipfs://bafybeihd7jkrilwpjxjnmtqm6u32645obignukwxmtivkvn4oxwqjk4hvm',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Eyepatch_b']: {
    color: 'b',
    image: 'ipfs://bafybeidcmwax2vtigz4em3l7flwtyr6j5jyzykyiuj2d4whwxtsrhxtxoe',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Eyepatch_c']: {
    color: 'c',
    image: 'ipfs://bafybeid5twd3jge5evtdrzcgyys7irtw2qz7flgpsielrxv2tv774psgci',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Eyepatch_d']: {
    color: 'd',
    image: 'ipfs://bafybeiddsegr7zn2q2uyjnirrk53b7qv7x5xbiixkhofcyprm46r37vpiu',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Eyepatch_e']: {
    color: 'e',
    image: 'ipfs://bafybeib5yqcrjlvd5ajtfbq3qdwhrj5icxrc3zzhk573ersfk5hf6lx46e',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Eyepatch_f']: {
    color: 'f',
    image: 'ipfs://bafybeicq6h2ome5xecaihotskokspla34nq6zmb5a5oya7ykj24vy4ihkm',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Eyepatch_g']: {
    color: 'g',
    image: 'ipfs://bafybeie3ilhvsynehc7nzmq7kjrcpaietm3hyimtc3qjsheulddp24w6si',
    trait_type: TraitType.EYES,
    variation: 'Eyepatch',
    z_index: 2,
  },
  ['2_Heavymakeup_a']: {
    color: 'a',
    image: 'ipfs://bafybeidmnxfjnm3bymmznykdumpget7c2mq34eg3ztkjvuowygdmudadze',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Heavymakeup_b']: {
    color: 'b',
    image: 'ipfs://bafybeiebyc55w6eu4ylyien54kkvwnntj3fiz6wxbaqvsoyqc7eej3n7la',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Heavymakeup_c']: {
    color: 'c',
    image: 'ipfs://bafybeia2ooinan5lzjjuzrag6wry4sc7qvnzdu6yfwdvyglsitconntmue',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Heavymakeup_d']: {
    color: 'd',
    image: 'ipfs://bafybeif4eficqyattmzcn3ay5qh6cyxd2babikkadiug532caobxkwna3q',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Heavymakeup_e']: {
    color: 'e',
    image: 'ipfs://bafybeifvh5cacwd4d5dl2e53hepuct66n5xz4efcvhkihurr5aubwocixi',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Heavymakeup_f']: {
    color: 'f',
    image: 'ipfs://bafybeibe5k376tayciptxwv5rw647azkv2mpp3n7xoesirpaixmew6vp4m',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Heavymakeup_g']: {
    color: 'g',
    image: 'ipfs://bafybeiaj6jnxnrgzsfxplqs7graoqhepjbiqxwnkg2teiikso3nudevfbe',
    trait_type: TraitType.EYES,
    variation: 'Heavymakeup',
    z_index: 2,
  },
  ['2_Makeup_a']: {
    color: 'a',
    image: 'ipfs://bafybeiewb5ihehdk2thzchv3b53n5disihhnria7xm5i7w3p4f6qdsd3mq',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['2_Makeup_b']: {
    color: 'b',
    image: 'ipfs://bafybeicjpr5yfaia7ubaazgtqcf7srwwcz7kea5g6m3rfnodmwqmabgnfe',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['2_Makeup_c']: {
    color: 'c',
    image: 'ipfs://bafybeih3gcxnvy3gtceuha2drnib2jezre3y7yg3etx3pbe3rhewv57xy4',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['2_Makeup_d']: {
    color: 'd',
    image: 'ipfs://bafybeid4wznmnsedj2r6omzafe6oaxiupid7gj3zlwrfoc27xrferygmnm',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['2_Makeup_e']: {
    color: 'e',
    image: 'ipfs://bafybeihghtgubvxriaimazvsw777sjmsuuxhndyrdymzbc27dkckglpqmm',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['2_Makeup_f']: {
    color: 'f',
    image: 'ipfs://bafybeid5eteqtbnpgaxayxboca5sn6k7y67oi7q2yzmvqeogaieen747oq',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['2_Makeup_g']: {
    color: 'g',
    image: 'ipfs://bafybeidby6etwjt3tfhuwmcjqvnqogijxttdi6t3lhxptdqmx7w6psfia4',
    trait_type: TraitType.EYES,
    variation: 'Makeup',
    z_index: 2,
  },
  ['3_Bald_a']: {
    color: 'a',
    image: 'ipfs://bafybeig42qzocwhc6fewtgvjdmi5cleq63j67xjik6xviwkn2q7psraz6e',
    trait_type: TraitType.HAIR,
    variation: 'Bald',
    z_index: 3,
  },
  ['3_Bald_b']: {
    color: 'b',
    image: 'ipfs://bafybeibenuklvq5dea7u7zviidokknsznvvidbyohldlnfpfiyakxjgwzy',
    trait_type: TraitType.HAIR,
    variation: 'Bald',
    z_index: 3,
  },
  ['3_Bald_c']: {
    color: 'c',
    image: 'ipfs://bafybeichwwqwreqkr2sfyzxezueupw63l7wtezzbcuge77uw5ykdfa3c5e',
    trait_type: TraitType.HAIR,
    variation: 'Bald',
    z_index: 3,
  },
  ['3_Bald_d']: {
    color: 'd',
    image: 'ipfs://bafybeibm4bxw24fab5ozd3muds3o4zvvuhrbdxuzdotxidqwfftosnigyq',
    trait_type: TraitType.HAIR,
    variation: 'Bald',
    z_index: 3,
  },
  ['3_Bald_e']: {
    color: 'e',
    image: 'ipfs://bafybeigrlrl7ricnvrs3lcgfk7a6ju5h5yzxbggm2wrj7ytbaho3eikple',
    trait_type: TraitType.HAIR,
    variation: 'Bald',
    z_index: 3,
  },
  ['3_Fade_a']: {
    color: 'a',
    image: 'ipfs://bafybeifv2frbulmliqw6lrmcsyxeiznicbppndekp34jz5xxtyjxjiz7pa',
    trait_type: TraitType.HAIR,
    variation: 'Fade',
    z_index: 3,
  },
  ['3_Fade_b']: {
    color: 'b',
    image: 'ipfs://bafybeigohd6xunt3656qnxgeshzx643g6566v7j5hpnm2sv76btfinmmpi',
    trait_type: TraitType.HAIR,
    variation: 'Fade',
    z_index: 3,
  },
  ['3_Fade_c']: {
    color: 'c',
    image: 'ipfs://bafybeiejq36ai3il5ail7nenw7cqt42lrgrzamjiozpfnstpo3ttc73qae',
    trait_type: TraitType.HAIR,
    variation: 'Fade',
    z_index: 3,
  },
  ['3_Fade_d']: {
    color: 'd',
    image: 'ipfs://bafybeifgalkuqfdsahxrk5w6ghzqu5ryta3pfm5ldyy2r7juihflmsptaq',
    trait_type: TraitType.HAIR,
    variation: 'Fade',
    z_index: 3,
  },
  ['3_Fade_e']: {
    color: 'e',
    image: 'ipfs://bafybeih52ednv42lhfo5bwkve2tx6hnmqarp5k77wch75ttdpxyatoa46m',
    trait_type: TraitType.HAIR,
    variation: 'Fade',
    z_index: 3,
  },
  ['3_Longhair_a']: {
    color: 'a',
    image: 'ipfs://bafybeibatqmxklpbiybbh27p27mh37af3audxnhdwo5r4ag4jacvaaj64e',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Longhair_b']: {
    color: 'b',
    image: 'ipfs://bafybeic4imf3wryi4wtt2rj6y27klhvnuedqw2baamo25amoguv47gnsje',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Longhair_c']: {
    color: 'c',
    image: 'ipfs://bafybeid5b4ci3b5hlrwwzz5n5enlgdxnajwmht65bgn54ohz732gddiohe',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Longhair_d']: {
    color: 'd',
    image: 'ipfs://bafybeihlentw6nne3xehh6u2dxsdylgchl2voccbkbpdg5yk3j7rwkmhqa',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Longhair_e']: {
    color: 'e',
    image: 'ipfs://bafybeigtek2atlebmwkhjs4gbodt2oqjptsh7nsq5ls4e5jdd5p26wziay',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Longhair_f']: {
    color: 'f',
    image: 'ipfs://bafybeiggdxmwvte2mjtjc5w2xmqmelhdu7ukfcutgszudc4ravzcaxzk6u',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Longhair_g']: {
    color: 'g',
    image: 'ipfs://bafybeia6t7lswgktwy3el5ckmvji7smwmgdyfxyt6maktjdu4dhuf2echq',
    trait_type: TraitType.HAIR,
    variation: 'Longhair',
    z_index: 3,
  },
  ['3_Mohawk_a']: {
    color: 'a',
    image: 'ipfs://bafybeid2oox3ykjgskklvufo74qyvqwrw6wnxpst7wmo5jd2zbtz57yasa',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  ['3_Mohawk_b']: {
    color: 'b',
    image: 'ipfs://bafybeifdxhqkdyhz6t2k2odrsierd465g3yx75pprnb6mocgiw5e42jhru',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  ['3_Mohawk_c']: {
    color: 'c',
    image: 'ipfs://bafybeibe5ornconlvb5w5g4lomzpyfdaegles3qfcsutaf5mzj5agi5hp4',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  ['3_Mohawk_d']: {
    color: 'd',
    image: 'ipfs://bafybeia4gl2p5vdtnp47flakyg3lll6b63twifvnbbc4codxt3vaesuu4q',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  ['3_Mohawk_e']: {
    color: 'e',
    image: 'ipfs://bafybeidosa52s5xibftgxt743k6avy6jodefchvaqgnlbsyov4udbjffue',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  ['3_Mohawk_f']: {
    color: 'f',
    image: 'ipfs://bafybeiat663g3om4viowy43fjjeyjy3wtnleie36ebsn47xn33xrtiudua',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  ['3_Mohawk_g']: {
    color: 'g',
    image: 'ipfs://bafybeiaziuovwlhpovtmrrqxf5ifp2syudgff3hjm6dsqxvv33l2vva3ge',
    trait_type: TraitType.HAIR,
    variation: 'Mohawk',
    z_index: 3,
  },
  // TODO: We still need to add a male villager outfit
  ['4_Villager2_a']: {
    color: 'a',
    image: 'ipfs://bafybeicgxsn52x5m5igscibcgxxdzp23iru3aehsrtltxnr2zsv5nduvca',
    trait_type: TraitType.CLOTHING,
    variation: 'Villager2',
    z_index: 4,
  },
  ['5_Basic_a']: {
    color: 'a',
    image: 'ipfs://bafybeif44rvzujcqc6zt74drdtfmmuzu5zagl74rtetpivv2vrsdju6fui',
    trait_type: TraitType.MOUTH,
    variation: 'Basic',
    z_index: 5,
  },
  ['5_Bigbeard_a']: {
    color: 'a',
    image: 'ipfs://bafybeic5pn5s25tmnxtyfmem54kzx4ovgjfrcbdym55tqhkjsstnl5p6fq',
    trait_type: TraitType.MOUTH,
    variation: 'Bigbeard',
    z_index: 5,
  },
  ['5_Bigbeard_b']: {
    color: 'b',
    image: 'ipfs://bafybeig5pelnntnzuqlalgznqhda6n2isgmrld37get5owujxxahcndepe',
    trait_type: TraitType.MOUTH,
    variation: 'Bigbeard',
    z_index: 5,
  },
  ['5_Bigbeard_c']: {
    color: 'c',
    image: 'ipfs://bafybeibuczbeaegn2ejnlzumv2kl62zig52qw6spn6r6anntnzkov6iljy',
    trait_type: TraitType.MOUTH,
    variation: 'Bigbeard',
    z_index: 5,
  },
  ['5_Bigbeard_d']: {
    color: 'd',
    image: 'ipfs://bafybeiadwzspf7m3r63jbe6wxvwsmr64ffusbjh4dh2pjf23hbnmgdgqke',
    trait_type: TraitType.MOUTH,
    variation: 'Bigbeard',
    z_index: 5,
  },
  ['5_Bigbeard_e']: {
    color: 'e',
    image: 'ipfs://bafybeibbti2s44nvmqw7daej34kyv5mditznyrmuiy3rajbjcjcremjjv4',
    trait_type: TraitType.MOUTH,
    variation: 'Bigbeard',
    z_index: 5,
  },
  ['5_Handlebars_a']: {
    color: 'a',
    image: 'ipfs://bafybeidaaua5amlafbxw2zxujii22sywubsks5yumfec7smp7pipjqx6ru',
    trait_type: TraitType.MOUTH,
    variation: 'Handlebars',
    z_index: 5,
  },
  ['5_Handlebars_b']: {
    color: 'b',
    image: 'ipfs://bafybeid4rgadocnctky6lwlwemprmt56c3vtxu7itglo6n45taybcf4kqm',
    trait_type: TraitType.MOUTH,
    variation: 'Handlebars',
    z_index: 5,
  },
  ['5_Handlebars_c']: {
    color: 'c',
    image: 'ipfs://bafybeig6plbkwjcff6x47djgjr7yddmvthwba5pcl4zftcune7ivstgblm',
    trait_type: TraitType.MOUTH,
    variation: 'Handlebars',
    z_index: 5,
  },
  ['5_Handlebars_d']: {
    color: 'd',
    image: 'ipfs://bafybeif6p6w4d7xahy77nf3bvl5mdchtqvm5op5lghaptfcyo3gj7fkmy4',
    trait_type: TraitType.MOUTH,
    variation: 'Handlebars',
    z_index: 5,
  },
  ['5_Handlebars_e']: {
    color: 'e',
    image: 'ipfs://bafybeic3d6c3ibklaqvfgmnwmzhnyvcwoalwl3m5b3fbgfwfq7cp3wlozy',
    trait_type: TraitType.MOUTH,
    variation: 'Handlebars',
    z_index: 5,
  },
  ['5_Lipstick_a']: {
    color: 'a',
    image: 'ipfs://bafybeid4sgr44nwxaq3ughizss6coypnicmbcgdgjmf2e7lzjbm2uxahda',
    trait_type: TraitType.MOUTH,
    variation: 'Lipstick',
    z_index: 5,
  },
  ['5_Lipstick_b']: {
    color: 'b',
    image: 'ipfs://bafybeibtkni43lohfyrod6ntncha7a4xhdxi5tcklfdiyiasyy6r52gffe',
    trait_type: TraitType.MOUTH,
    variation: 'Lipstick',
    z_index: 5,
  },
  ['5_Lipstick_c']: {
    color: 'c',
    image: 'ipfs://bafybeifx3a2xjou377wuegare6o4sanwuwvashjpluj7kk2dtx6wskm6ti',
    trait_type: TraitType.MOUTH,
    variation: 'Lipstick',
    z_index: 5,
  },
  ['5_Lipstick_d']: {
    color: 'd',
    image: 'ipfs://bafybeihr4fvlgwd6hq3bc4s4kc7tx44zc4stpx37k6yfv5nhy2iuvjbc24',
    trait_type: TraitType.MOUTH,
    variation: 'Lipstick',
    z_index: 5,
  },
  ['5_Lipstick_e']: {
    color: 'e',
    image: 'ipfs://bafybeibzc4zzbz5xkq7zmg66meblh4g4tewmfkzz4etez3ss57dfbsmzmu',
    trait_type: TraitType.MOUTH,
    variation: 'Lipstick',
    z_index: 5,
  },
};

export const BODY_TRAITS = Object.values(TRAITS).filter(
  trait => trait.trait_type === TraitType.BODY,
);

export const EYES_TRAITS = Object.values(TRAITS).filter(
  trait => trait.trait_type === TraitType.EYES,
);

export const HAIR_TRAITS = Object.values(TRAITS).filter(
  trait => trait.trait_type === TraitType.HAIR,
);

export const CLOTHING_TRAITS = Object.values(TRAITS).filter(
  trait => trait.trait_type === TraitType.CLOTHING,
);

export const MOUTH_TRAITS = Object.values(TRAITS).filter(
  trait => trait.trait_type === TraitType.MOUTH,
);

export const formatFileName = (trait: Trait): string =>
  `${trait.z_index}_${trait.variation}_${trait.color}`;

export const getImageUrl = (trait: Trait): string => {
  const fileName = formatFileName(trait);
  return uriToHttp(trait.image)[0] + fileName + '.png';
};
